# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from AES_Ui import Ui_Frame as AF
from DES_Ui import Ui_Frame as DF
from About_Us import Ui_Frame as AU
from AES import Metode_AES as MAES
from DES import Metode_DES as MDES

class AES(QtWidgets.QFrame,AF):
    def __init__(self,parent=None):
        super(AES,self).__init__(parent)
        self.setupUi(self)
    
class DES(QtWidgets.QFrame,DF):
    def __init__(self,parent=None):
        super(DES,self).__init__(parent)
        self.setupUi(self)

class About(QtWidgets.QFrame,AU):
    def __init__(self,parent=None):
        super(About,self).__init__(parent)
        self.setupUi(self)
        
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.AESX=AES()
        self.DESX=DES()
        self.Aboutx=About()
        
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 720))
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

       
        
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../Assets/main frame/Picture1.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(360, 400, 231, 81))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Assets/main frame/to_aes_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(230, 120))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(700, 400, 231, 81))
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Assets/main frame/to_des_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(230, 120))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(570, 510, 161, 41))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setIconSize(QtCore.QSize(170, 120))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(570, 220, 150, 150))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../Assets/main frame/Merah-Putih-Doge.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(390, 110, 500, 100))
        self.label_3.setMinimumSize(QtCore.QSize(500, 100))
        self.label_3.setMaximumSize(QtCore.QSize(500, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.pushButton.clicked.connect(lambda:[MainWindow.hide(),self.AESX.show()])
        self.pushButton_2.clicked.connect(lambda:[MainWindow.hide(),self.DESX.show()])
        self.pushButton_3.clicked.connect(lambda:[MainWindow.hide(),self.Aboutx.show()])

        self.AESX.pushButton.clicked.connect(lambda:[self.AESX.hide(),MainWindow.show()])
        self.DESX.pushButton.clicked.connect(lambda:[self.DESX.hide(),MainWindow.show()])
        self.Aboutx.pushButton.clicked.connect(lambda:[self.Aboutx.hide(),MainWindow.show()])

        self.AESX.pushButton_2.clicked.connect(lambda:[self.AES_EN()])
        self.AESX.pushButton_3.clicked.connect(lambda:[self.AES_DE()])
        self.DESX.pushButton_2.clicked.connect(lambda:[self.DES_EN()])
        self.DESX.pushButton_3.clicked.connect(lambda:[self.DES_DE()])
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def AES_EN(self):
        A=MAES(bytes(self.AESX.plainTextEdit_6.toPlainText(),'utf-8'),"",bytes(self.AESX.plainTextEdit_2.toPlainText(),'utf-8'),"","")
        A.Enkripsi()
        self.AESX.plainTextEdit_8.setPlainText(str(A.cipher))
        self.AESX.plainTextEdit_4.setPlainText(str(A.tag))
        self.AESX.plainTextEdit_5.setPlainText(str(A.nonce))
    def AES_DE(self):
        X=[self.AESX.plainTextEdit_12.toPlainText()[2:-1],self.AESX.plainTextEdit_11.toPlainText()[2:-1],self.AESX.plainTextEdit_10.toPlainText()[2:-1]]
        Y=[]
        Y.append(X[0].encode().decode('unicode_escape').encode('raw_unicode_escape'))
        Y.append(X[1].encode().decode('unicode_escape').encode('raw_unicode_escape'))
        Y.append(X[2].encode().decode('unicode_escape').encode('raw_unicode_escape'))
        A=MAES("",Y[0],bytes(self.AESX.plainTextEdit_9.toPlainText(),'utf-8'),Y[1],Y[2])
        A.Dekripsi()
        self.AESX.plainTextEdit_7.setPlainText(str(A.plain)[2:-1])
    def DES_EN(self):
        D=MDES(bytes(self.DESX.textEdit.toPlainText(),'utf-8'),"",bytes(self.DESX.textEdit_2.toPlainText(),'utf-8'),self.DESX.comboBox.currentText())
        D.Enkripsi()
        self.DESX.textEdit_3.setPlainText(str(D.cipher))
    def DES_DE(self):
        X=self.DESX.textEdit_5.toPlainText()[2:-1]
        D=MDES("",X.encode().decode('unicode_escape').encode('raw_unicode_escape'),bytes(self.DESX.textEdit_6.toPlainText(),'utf-8'),self.DESX.comboBox_2.currentText())
        D.Dekripsi()
        self.DESX.textEdit_4.setPlainText(str(D.plain.decode()))
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_3.setText(_translate("MainWindow", " About Us !"))
        self.label_3.setText(_translate("MainWindow", "AES DES Converter"))


if __name__ == "__main__":
    import sys
    
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
